### PR TITLE
Allow using colon, semicolon and equal sign in completions

### PR DESCRIPTION
**Pull request by DannyBen**
Raised and discussed in #66 

This PR temporarily (locally) removes three characters from the list of word break characters: colon, semicolon, equal sign.

### CODE REVIEW

**Review by kronn — APPROVED** [review]
I think I need to add these approvals to my setup for scripts, looks really neat.

Changewise, I like that the change is sensibly small, local and reverted after its use.

**Comment by DannyBen** [comment]
> I think I need to add these approvals to my setup for scripts, looks really neat.

[rspec_approvals](https://github.com/dannyben/rspec_approvals) is a massive time saver for my tests, even more so in command line utilities.

I will merge. Release will be coming later this week (you can use the edge in the meantime).

**Comment by kronn** [comment]
It seems like the locally set env-var does not work as intended. With the generated script, I did not get the intended completion-behaviour. Maybe hold off on a release, I'd like to try to fix this today or tomorrow.

**Comment by DannyBen** [comment]
You are right. I think that disabling it broke it.
Placing it right before calling `complete`:

```
COMP_WORDBREAKS="${COMP_WORDBREAKS//[:=]/}" complete -F _asd_completions asd
```

works, but seems to affect the global state.

**Comment by DannyBen** [comment]
> npm had a similar problem: [npm/npm@d7271b8](https://github.com/npm/npm/commit/d7271b8226712479cdd339bf85faf7e394923e0d)

I see that they reverted?
Setting the environment variable globally is definitely not a solution, due to the *sourced* nature of completion scripts.

There must be a way to change this temporarily - did you follow the npm thread to see if they solved it in a different way? Or did they just revert and left it unsolved?

I was unable to get any better solutions from any of the chat AIs.

**Comment by kronn** [comment]
They reverted the way with the env-var, not their custom parsing: https://github.com/npm/cli/blob/latest/lib/utils/completion.sh

I'll try and see if I can get it to work similarly.

**Comment by DannyBen** [comment]
Should I revert this PR, or are you trying to make it work?

**Comment by kronn** [comment]
Both. :-) 
Sorry for the late repsonse.

If I get to a solution, I'll send a PR.

**Pull request merged**
