### PR TITLE
Add doc references

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**

### CODE REVIEW

**Review by DannyBen — APPROVED** [review]

**Comment by EmilySeville7cfg** [comment]
PR is ready to merge. ;)

**Comment by DannyBen** [comment]
Wait - what is the .vscode folder? What does it do?
Not sure I am interested in including editor specific configs...

**Comment by EmilySeville7cfg** [comment]
> Wait - what is the .vscode folder? What does it do?

This folder contains VS Code specific settings to enable hints in .yaml files like [here](https://github.com/DannyBen/bashly/blob/master/.vscode/settings.json).

> Not sure I am interested in including editor specific configs...

There is no way to enable intellisence otherwise. So if we remove user should setup intellisence manually. I suggest then to remove `.vscode` folders from everywhere and just document how to recreate them and what contents with.

**Comment by DannyBen** [comment]
Ok... didn't notice we already have this in bashly.

1. Can you screenshot how it looks? Preferably in bashly, where it seems more meaningful
2. Where is the `fixtures` folder that it references? Do you mean `spec/fixtures`? This folder cannot be relied upon for anything other than specs

> I suggest then to remove .vscode folders from everywhere and just document how to recreate them and what contents with.

1. Wait before removal, I am still on the fence.
2. I do not necessarily agree that there is any need to ship editor configs.

**Comment by EmilySeville7cfg** [comment]
> Can you screenshot how it looks? Preferably in bashly, where it seems more meaningful

image

image

image
> Where is the fixtures folder that it references? Do you mean spec/fixtures? This folder cannot be relied upon for anything other than specs

Yep, I mean **spec/fixtures**.

**Comment by DannyBen** [comment]
Ok, thanks for the screens - it is clear now.

I don't think it is necessary here.
I am ok with either keeping or removing it from bashly.

**Comment by EmilySeville7cfg** [comment]
So, should I remove it here?

**Comment by DannyBen** [comment]
> So, should I remove it here?

Yes please.

**Pull request merged**
